kruskal_mst: kruskal_mst.cc
	clang++ -std=c++1y -o $@.test -D TEST $^
prim_mst: prim_mst.cc
	clang++ -std=c++1y -o $@.test -D TEST $^
prim_msf: prim_msf.cc
	clang++ -std=c++1y -o $@.test -D TEST $^

clean:
	rm *.test

